"""init table

Revision ID: 16aaaa7ca3f0
Revises: bfcd62e78292
Create Date: 2026-05-31 01:35:02.915573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '16aaaa7ca3f0'
down_revision: Union[str, Sequence[str], None] = 'bfcd62e78292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('role', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'deleted_at')
    op.drop_column('role', 'updated_at')
    # ### end Alembic commands ###
