"""create user role permission table

Revision ID: 171e07f62c91
Revises: 7efbb2e961f3
Create Date: 2026-05-31 01:49:38.268906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '171e07f62c91'
down_revision: Union[str, Sequence[str], None] = '7efbb2e961f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'role', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'created_by_id')
    # ### end Alembic commands ###
