"""add owner on table user

Revision ID: c8a15d3ba23e
Revises: 9eba36f5ada5
Create Date: 2026-05-23 23:50:02.509166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c8a15d3ba23e'
down_revision: Union[str, Sequence[str], None] = '9eba36f5ada5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('user_created_by_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['owner_id'], ['id'])
    op.drop_column('user', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_created_by_id_fkey'), 'user', 'user', ['created_by_id'], ['id'])
    op.drop_column('user', 'owner_id')
    # ### end Alembic commands ###
