"""add owner on table user

Revision ID: e5b8e3a38576
Revises: d596bff10ffb
Create Date: 2026-05-23 15:03:12.887380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e5b8e3a38576'
down_revision: Union[str, Sequence[str], None] = 'd596bff10ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'owner_id')
    # ### end Alembic commands ###
